[build]
publish = "_site"
# remove any 'command' here—let the plugin handle it

[[plugins]]
package = "@quarto/netlify-plugin-quarto"

  [plugins.inputs]
  # install the latest Quarto release
  version = "latest"
  # only render HTML (skip PDF)
  cmd = "render --to html"